# Netlify configuration file
# This ensures that all routes are handled by the single page application

[build]
  publish = "dist"
  command = "npm run build"

# Redirect all requests to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200